### ISSUE TITLE
"Team lives remaining" is wrong

### ISSUE THREAD

**Issue by EboMike** [spookybear0/laserforce_ranking#94]
https://laserforce.spoo.uk/game/sm5/184

Fire team has one player with 4 lives, but total shows 0 lives.

**Comment by EboMike** [comment]
Oh wait, that's average. I played myself by mixing average and minimum in the "totals". Maybe all averages should have decimal point to make it more obvious.

**Comment by spookybear0** [comment]
Doesn't it make more sense for lives specifically to be total rather than an average?

**Comment by EboMike** [comment]
Both kinda make sense in their own way.... but I think I'll just make it the total. Otherwise I'd have to change the data model, since it's currently an integer for the column.

**Comment by EboMike** [comment]
Okay, I changed it to sum for lives and shots. Honestly it's a bit weird. I think average makes more sense.
