### ISSUE TITLE
Matchmaking sometimes yields uneven players

### ISSUE THREAD

**Issue by spookybear0** [spookybear0/laserforce_ranking#95]

**Comment by EboMike** [comment]
Test case:
![Screenshot_20240707-181135](https://github.com/spookybear0/laserforce_ranking/assets/175222/59b23a76-4f6d-4e5f-965d-da4ab466b0b8)

**Comment by spookybear0** [comment]
This should be fixed, I added some extra checks but there's no exact way for me to test it (commit 0774be7).
